### ISSUE TITLE
[Bug] GetOriginalModPackJsonData has wrong parameter type/wrong commentary

### ISSUE THREAD

**Issue by ghost** [liinko/xivModdingFramework#14]
Hi,

xivModdingFramework.Mods.FileTypes.GetOriginalModPackJsonData takes a parameter of type 'DirectoryInfo' but fails if this is actually a directory.

Either the comment needs to be fixed to describe that it should actually be the zip file containing the data of the modpack and the parameter type should be switched to 'FileInfo' or the method should at least have an `if` clause querying if the parameter is actually a zip file and if not, throw a proper exception.

(Disclaimer: I'm not using this project, just helping someone who wants to use this library/project)

**Comment by liinko** [comment]
Taking a look, it seems I used DirectoryInfo for everything, so there are several instances where a file is expected, I will be changing these cases to FileInfo and updating the comments.

I will also update the comments with what is expected from the input, in this case it is a zip archive containing a json file with extension .mpl and a binary data file with extension .mpd, the zip file having a custom extension (.ttmp2) as can be seen in the CreateSimpleModPack method.

**Comment by lillelilje** [comment]
That's awesome news, thank you! :)
